# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:4.10


# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test
  - build
  - assets

test:
  stage: test
  script: gradle --build-cache clean test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  only:
    - master
    - tags
  except:
    - branches

build:
  stage: build
  script: gradle bintrayUpload
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    expire_in: 1 day
    paths:
      - ./build/libs/*.jar
  only:
    - tags
  except:
    - branches

append_assets:
  stage: assets
  # We use the openjdk image here because it's smaller than the docker image.
  image: openjdk:8-jdk-slim
  script:
    - chmod +x appender.jar
    - java -jar appender.jar -d "./build/libs/"
  only:
    - tags
  except:
    - branches